version: '3'

services:
  youtube_stream_rest_api:
    build:
      context: ./youtube_stream_image
      dockerfile: Dockerfile
    image: youtube_stream_rest_api
    container_name: youtube_stream
    volumes:
      - ./youtube_stream_image/code:/code
    ports:
      - 8888:8888
    environment:
      - YOUTUBE_LIVE_KEY=<YOUR_YOUTUBE_LIVE_STREAM_KEY>
    devices:
      - /dev/video0:/dev/video0
    entrypoint:
      - python3
      - /code/stream_rest_api.py
    tty: true
  device_scan_rest_api:
    build:
      context: ./device_scanner_image
      dockerfile: Dockerfile
    image: device_scanner_rest_api
    container_name: device_scanner
    volumes:
      - ./device_scanner_image/code:/code
    ports:
      - 8887:8887
    network_mode: "host"
    entrypoint:
      - python3
      - /code/device_scan_rest_api.py
    tty: true
  master_app:
    build:
      context: ./master_app_image
      dockerfile: Dockerfile
    image: master_app
    container_name: master_app
    volumes:
      - ./master_app_image/code:/code
    network_mode: "host"
    entrypoint:
      - python3
      - /code/start_app.py
    depends_on:
      - device_scan_rest_api
      - youtube_stream_rest_api
    tty: true
